
/**
* ShapeListOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from SHAPE.idl
* Wednesday, March 19, 2003 6:29:50 PM GMT
*/

public interface ShapeListOperations 
{
  Shape newShape (GraphicalObject g) throws ShapeListPackage.FullException;
  Shape[] allShapes ();
  int getVersion ();
} // interface ShapeListOperations
