import java.rmi.*;
import java.util.Vector;

/**
* ShapeList.java 
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from SHAPE.idl
* Wednesday, March 19, 2003 6:29:50 PM GMT
*/

public interface Shape extends Remote {
    int getVersion() throws RemoteException;
    GraphicalObject getAllState() throws RemoteException;
}

public interface ShapeList extends Remote, ShapeListOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
    Shape newShape(GraphicalObject g) throws RemoteException;
    Vector allShapes() throws RemoteException;
    int getVersion() throws RemoteException;
} // interface ShapeList
