/**
* ShapeList.java 
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from SHAPE.idl
* Wednesday, March 19, 2003 6:29:50 PM GMT
*/

public interface ShapeList extends ShapeListOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ShapeList
