import java.rmi.*;
import java.util.Vector;

/**
 * 
 * ShapeList.java 
 * Generated by the IDL-to-Java compiler (portable), version "4.0"
 * from SHAPE.idl
 * Tuesday, June 23, 2015 18:39:00 PM GMT
 * 
 * @author: Francisco Maria Calisto
 * 
 */

public interface Shape extends Remote {
    int getVersion() throws RemoteException;
    GraphicalObject getAllState() throws RemoteException;
}

public interface ShapeList extends Remote, ShapeListOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
    Shape newShape(GraphicalObject g) throws RemoteException;
    Vector allShapes() throws RemoteException;
    int getVersion() throws RemoteException;
} // interface ShapeList
